name: Build and Deploy With Docker

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/chargingpot
  VERSION: ${{ github.sha }}
  NAME: cicdtest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Build with Gradle
        run: |
          cd chargingpot
          ./gradlew build

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-cicdtest ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .
          docker push ${{ env.DOCKER_IMAGE }}:latest
      
      - name: Deploy to self-hosted server
        run: |
          docker run -d -p 8080:8080 --name cicdtest --restart always ${{ env.DOCKER_IMAGE }}:latest
